version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: shopify-api-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - shopify-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
# Uncomment below if you want to mount code for live reload in dev
# volumes:
#   - ./:/app 
#   - /app/venv  # Exclude virtual environment from mount

networks:
  shopify-network:
    driver: bridge 